#!/bin/bash


BLUE='\033[0;34m'
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

welcome () {
    clear

cat <<'MSG'

        ``
     `/+++/-`
     :+++++++:`
     /++++++oo+:
     /++oooooooo/`
    :/ooooooooooo+`                .:/.
    ::+oooooooooss+               :+++/:.
    .::+ooooossssss/            `/ooo+/:-
     -//+osssssssyyy:          `+oooo+::.
      .://+sssyyyyyyy.        `ossooo/:-
       `-://+syyyyhhhy`      `oyssss/:-
         `-://+syhhhhho      oyyyys/:-
            `-:/+oyhddd/    ohhhyo/-`
               `.-:/oydd.  +dhy+:.`
                    `.-// -o/-.
                  -/+++/. `:+++/.
                 `sssso.    :osso
                  -/+/`      .++.

            Butterfly.CMS with Docker
       (c) 2019-2020 W.D.M.Group, Ukraine

MSG
}

welcome

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error!${NC} It looks like ${BLUE}Docker Machine${NC} is not installed. Please install it to continue and try again."
    echo "For help getting started, check out the docs at https://docs.docker.com"
    echo ""
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}Error!${NC} It looks like ${BLUE}Docker Composer${NC} is not installed. Please install it to continue and try again."
    echo "For help getting started, check out the docs at https://docs.docker.com"
    echo ""
    exit 1
fi

select_env () {

    echo ""
    echo "Select the environment you want to build:";
    echo "  1) Nginx + PHP-FPM with MySQL";
    echo "  2) Nginx + PHP-FPM with PostgreSQL";
    echo "  3) Apache + PHP with MySQL";
    echo "  4) Apache + PHP with PostgreSQL";
    echo ""
    read  -n 1 -p "Your choice: " environment
    echo ""
    echo ""

    if [ "$environment" = "1" ]; then
        docker-compose -f ./templates/nginx-mysql/docker-compose.yml build --no-cache --force-rm
    elif [ "$environment" = "2" ]; then
        docker-compose -f ./templates/nginx-postgres/docker-compose.yml build --no-cache --force-rm
    elif [ "$environment" = "3" ]; then
        docker-compose -f ./templates/apache-mysql/docker-compose.yml build --no-cache --force-rm
    elif [ "$environment" = "4" ]; then
        docker-compose -f ./templates/apache-postgres/docker-compose.yml build --no-cache --force-rm
    else
        echo -e "${RED}You have entered an invalid selection!${NC}"
        echo "Please try again!"
        echo ""
        echo "Press any key to continue..."
        read -n 1
        clear
        select_env
    fi
}

select_env