version: '3'
services:
  db:
    build:
      context: ./db/mysql
    user: "1000:50"
    environment:
      MYSQL_HOST: ${MYSQL_DB_HOST}
      MYSQL_PORT: ${MYSQL_DB_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    networks:
      - backend
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db/mysql/data:/docker-entrypoint-initdb.d
      - ./logs/mysql/:/var/log/mysql:delegated
      - db-data:/var/lib/mysql

  php:
    build:
      context: ./php
    environment:
      DB_TYPE: 'mysql'
      DB_HOST: ${MYSQL_DB_HOST}
      DB_PORT: ${MYSQL_DB_PORT}
      DB_NAME: ${MYSQL_DB_NAME}
      DB_USER: ${MYSQL_DB_USER}
      DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      PHP_IDE_CONFIG: serverName=butterfly.cms
    volumes:
      - web-data
    networks:
      - frontend
      - backend
    depends_on:
      - db

  web:
    build:
      context: ./web/nginx
    environment:
      FASTCGI_PASS_HOST: php
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx/:/var/log/nginx/:delegated
      - web-data:/var/www/public
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - php

networks:
  frontend:
  backend:
    driver: bridge

volumes:
  db-data:
  web-data: